#!/bin/bash

#apt proxy
echo 'Acquire::http::proxy "http://aptproxy:3142";' > /etc/apt/apt.conf.d/02proxy
echo 'Acquire::https::proxy "http://approxy:3142";' >> /etc/apt/apt.conf.d/02proxy

#clean apt cache since we use apt-proxy-ng
cat > /etc/cron.hourly/apt-clean << EOF
#!/bin/bash
apt-get clean
EOF
chmod +x /etc/cron.hourly/apt-clean

#upgrades
apt-get -y install unattended-upgrades
echo "APT::Periodic::Update-Package-Lists \"1\";" > /etc/apt/apt.conf.d/20auto-upgrades
echo "APT::Periodic::Unattended-Upgrade \"1\";" >> /etc/apt/apt.conf.d/20auto-upgrades

#timezone
echo 'US/Central' > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata
